### ISSUE TITLE
Bold Version?

### ISSUE THREAD

**Issue by hbjydev** [ntk148v/vim-horizon#1]
Could you make the bold version? :D

Nice work btw

**Comment by ntk148v** [comment]
Thank you :100: 

Normal version:

![image](https://user-images.githubusercontent.com/10803803/63661505-0eb9b300-c7e5-11e9-9549-172a5d0808de.png)

Bold statement version:

![image](https://user-images.githubusercontent.com/10803803/63661527-25f8a080-c7e5-11e9-9bcb-85c5c6b90e1e.png)

You mean this?

**Comment by hbjydev** [comment]
Yeeep.

**Comment by ntk148v** [comment]
Done! :rocket:

**Comment by hbjydev** [comment]
Thanks! :D
