### ISSUE TITLE
ERROR: There are not enough colors - after upgrading to NeoVim 0.8

### ISSUE THREAD

**Issue by Hamm-J** [ntk148v/vim-horizon#10]
**Describe the bug**
I upgraded NeoVim to v0.8.0 release and am now receiving the following error when I try to use Horizon colorscheme:
```
shell=/bin/zsh
Error detected while processing /Users/jason/.config/nvim/init.vim[52]../Users/jason/.config/nvim/autoload/plugged/vim-horizon/colors/horizon.vim:
line   11:
[Horizon] There are not enough colors.
```

In my init.vim, I have `termguicolors` enabled and am using Alacritty v0.11.0, which supports terminal gui colors:

```
colorscheme horizon
if has('termguicolors')
    set termguicolors
endif
```

The theme was working just fine before I upgraded NeoVim to 0.8.

**To Reproduce**

1. Upgrade NeoVim to version 0.8 release
2. Set Horizon to Vim theme in `init.vim`:
```
colorscheme horizon
if has('termguicolors')
    set termguicolors
endif
```
3. Open terminal that supports gui colors (Alacritty)
4. Error appears when launching NeoVim

**Desktop (please complete the following information):**
OS: MacOS Monterey 12.6
Vim: NeoVim 0.8
Terminal: Alacritty 0.11.0 (Also apears in iTerm2).

Thanks in advance for any and all help! My apologies if this is a simple error, to resolve I'm still getting used to the Vim ecosystem and haven't had time to look through the API changes in the new NeoVim release.

Also, thanks for maintaining this color scheme, I absolutely love it! :-)

**Comment by ntk148v** [comment]
Hi @Hamm-J thank for using my colorscheme. Let's me take a look at this one

**Comment by ntk148v** [comment]
Hi @Hamm-J sorry for the late response. There is nothing wrong with vim-horizon ^^

Just change your config:

```vim
if has('termguicolors')
    set termguicolors
endif
" Set your termguicolors before enable horizon
colorscheme horizon
```

**Comment by Hamm-J** [comment]
Thank you so much for your help! I switched the order of the color scheme and termguicolors and it works again :-) back to the beautiful colors!

**Comment by ntk148v** [comment]
Great, let's close this one.
