### ISSUE TITLE
E254: cannot allocate colour none

### ISSUE THREAD

**Issue by hbjydev** [ntk148v/vim-horizon#2]
https://shrt.haydennyyy.com/XNDTm9ctWUw7.png

I got this error when I ran :PlugUpdate with `colo horizon` set in my `_vimrc`.

**Comment by ntk148v** [comment]
![image](https://user-images.githubusercontent.com/10803803/64058697-17d9c400-cbd9-11e9-9b1b-35a90acf609e.png)

I couldn't reach your site :sob: 
Btw, i'm really glad that someone like my work!!! :rocket:

**Comment by hbjydev** [comment]
Oh, yeah, my hosting provider's having downtime issues rn. But it's an
error that gVim shows when I use the updated bold version.

**Comment by liyz15** [comment]
Exactly same issue here, the error says
```
Error detected while processing $HOME/.vim/plugged/vim-horizon/colors/horizon.vim:
line   54:
E254: Cannot allocate color none
Press ENTER or type command to continue
```

Vim8 + iterm2 + MacOS
The color scheme doesn't look right even if I changed none to NONE.

**Comment by ntk148v** [comment]
Oh, I knew which the cause: https://github.com/neovim/neovim/issues/9045 I'm using Neovim so  `NONE` is acceptable value. :bowing_man: Thank you, the fix is coming quickly.

**Comment by ntk148v** [comment]
@liyz15 @haydennyyy please re-check and feel free to reopen issue if thing doesn't work as expected.

**Comment by hbjydev** [comment]
Okay, so I updated but I think gVim doesn't support bold text... Which is really weird.

**Comment by hbjydev** [comment]
Wait, no. I think bold text doesn't work on the Windows version of Vim. @ntk148v What's Neovim like vs regular Vim? I might have to switch for this color scheme.

**Comment by ntk148v** [comment]
@haydennyyy hi, sorry for the late response. Let me do further check, might be the difference between term and gui font.

**Comment by ntk148v** [comment]
@haydennyyy could you test it again? It should work at this time.

**Comment by hbjydev** [comment]
@ntk148v Sorry for *my* late response now, lol. It's working fine :)
