### ISSUE TITLE
Transparent background option for terminal (neo)vim

### ISSUE THREAD

**Issue by chaitanyabsprip** [ntk148v/vim-horizon#6]
Should add support for transparent background similar to dracula, gruvbox and other such color schemes.

-- also could you please put a picture of the color pallette in the readme.md.

**Comment by ntk148v** [comment]
Hi @Chaitanyabsprip , thank you, sounds nice.

**Comment by chaitanyabsprip** [comment]
#7

**Comment by ntk148v** [comment]
Color palette: https://github.com/ntk148v/vim-horizon#color-palette
